version: '3.4'

services:
  forumdb:
    container_name: forumdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=0000
    ports:
      - 5432:5432 
  forum.webapi:
    container_name: webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
    depends_on:
      - forumdb
  frontend:
    container_name: frontend
    ports:
      - "3000:3000"