version: '3.4'

services:
  forum.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80:8080"
      - "443:8081"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  frontend:
    ports:
      - "3000:3000"